# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hTG9MKA5aLV6FGiYfZ520rWliiX2_M9G
"""

from google.colab import files
supermarket=files.upload()

from google.colab import files
teams=files.upload()

import pandas
teamgoals={"teams":['spain','england'],'goals':[2,4]}
teamgoaldf=pandas.DataFrame(teamgoals)
print(teamgoaldf)

import pandas as pd
a={'players':['neymar','ronaldo'],'country':['brazil','portugal']}
fbdf=pd.DataFrame(a)
print(fbdf)

import pandas as pd
dataframe=pd.read_csv("Supermarket_sales.csv")
print(dataframe)

print(dataframe.head())

print(dataframe.tail())

dataframe['City']



dataframe['Branch']

dataframe['Branch'and'City']

print(dataframe.index)

for i in dataframe.index:
  print(dataframe.City[i],dataframe.Branch[i])



from google.colab import files
players=files.upload()

import pandas
fifadataframe=pandas.read_csv("players_20.csv")
max_overall=fifadataframe.age.idxmax()
#max_overall_loc=fifadataframe.overall.idxmax()
person=fifadataframe.loc[max_overall_loc]
print(max_overall)
#print(person.long_name,"has the highest overall of",max_overall)

playercount=fifadataframe.sofifa_id.count()
print(playercount)

overall_average=fifadataframe.overall.mean()
print(overall_average)

for i in fifadataframe.index:
  if fifadataframe.club[i]=="FC Barcelona":
    print(fifadataframe.short_name[i])

