# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fU_0dK28o7lHZyxBaVQkvH9Ac8pylH2z
"""

def fun_name():
  print("fifa world cup 2022")
fun_name()

def fun_name(x,y,z):
   print(x,y,z)
fun_name("rose","saffron","wood")

def abc(*x):
  print("the first favourite football ",x[2])
abc("messi","ronaldo","neymar")

